#import "@local/mindtape:0.2.0": *

#show: task.with(
  title: "README generated from Typst under 100 lines, drift gated",
  status: done(2026, 10, 2),
)

== Summary
README.md is 250 lines, restates the tool description and the e2e script
header, cites the author's local paths, and its sample list output no longer
matches what the tool prints.

Rewrite it from `docs/readme.typ`, rendered with typlite (the mindtape
approach). Facts that code can produce — the reference table, a real list
output — are generated by running the code, never typed. `just check` fails
when README.md differs from a fresh render. What generation cannot tie
together — the skill and README prose against the tool's behaviour — is an
outdatty group. Under 100 lines.
