#:schema https://raw.githubusercontent.com/mlavrinenko/mindtape/main/schema/config.schema.json
[tasks]
[[tasks.roots]]
path = "tasks"
derive-tags = true

[tasks.derive-tags]
enabled = true
collect = ["segments"]

[[tasks.status]]
value = "proposed"
glyph = "💡"
color = "blue"
to = ["wip", "cancelled"]

[[tasks.status]]
value = "wip"
glyph = "🔨"
color = "yellow"
to = ["blocked", "done", "cancelled"]

[[tasks.status]]
value = "blocked"
glyph = "🔒"
color = "red"
to = ["wip", "cancelled"]

[[tasks.status]]
value = "done"
glyph = "✅"
color = "green"
terminal = true
to = ["wip"]

[[tasks.status]]
value = "cancelled"
glyph = "🚫"
color = "magenta"
terminal = true
